### ISSUE TITLE
Messages in DokuWiki deprecated log

### ISSUE THREAD

**Issue by Autumnf0x** [turnermm/newpagetemplate#11]
Messages in DokuWiki deprecated log:
`require(action.php) is deprecated. It was called from require() in /var/www/dokuwiki/lib/plugins/newpagetemplate/action.php:20 Autoloading should be used instead!`

- newpagetemplate Plugin version: 2022-02-05;
- DokuWiki version: 2023-04-04a "Jack Jackrum";
- PHP 8.2;

> The plugin eliminates a lot of routine. I really, really hope it's still maintained.

**Comment by Autumnf0x** [comment]
> Comment out lines 20 and 21 in action.php and let me know the result

sure
```
/*
require_once(DOKU_PLUGIN.'action.php');
require_once(DOKU_INC.'inc/init.php');
*/
```
Deprecated log is disapear, and... didn't show up anymore.
Leave it like that? Maybe... commit, new version, etc.?

**Comment by turnermm** [comment]
Would you be able to adopt this plugin? After many years with DW I am no longer playing an active role, and I am looking for users to take over my plugins.  You can check on GitHub at turnermm. 
https://forum.dokuwiki.org/d/21534-retiring

**Comment by Autumnf0x** [comment]
Of course, it’s a pity when good plugins remain without support. The plugin newpagetemplate , in particular, solved many templating problems. In any case - thank you very much! And, I hope the popularity of plugins will ultimately affect the succession in terms of their support.
Thank you again and wish you all the best. :)

**Comment by dregad** [comment]
I can't believe I had this fixed locally nearly 5 months ago, and I forgot to push the changes :/
