### ISSUE TITLE
Date/time-based naming not working for me

### ISSUE THREAD

**Issue by d-elgui** [turnermm/newpagetemplate#14]
Greetings! 

The Date/time-based naming is not working for me. For instance, the following example syntax:

`{{NEWPAGE>journal:%Y-%m-%d?autopage}}`

...shows a input box that creates the following page when filled with "test": 

`y-_m-_d_autopage:test`

Is it a known issue?

My current Dokuwiki install:
Release 2024-02-06b "Kaos"
Template Bootstrap3 v2024-02-06 (stable/20240206)

**Comment by dregad** [comment]
> Is it a known issue?

Yes, see https://github.com/dregad/dokuwiki-plugin-addnewpage/issues/98#issuecomment-2061545148
