### ISSUE TITLE
XSS vulnerability in write_msg()

### ISSUE THREAD

**Issue by splitbrain** [turnermm/newpagetemplate#2]
See http://php-grinder.com/vulns/view/1193317

$_REQUEST['newpagetemplate'] is output without escaping.

**Comment by turnermm** [comment]
escaped output with htmlentities.

**Comment by turnermm** [comment]
Escaping output string wasn't enough for grinder; I had to use $INPUT to get an OK from it.  
http://php-grinder.com/project/view/22070
I'm not sure how trustworthy grinder is here.  It gives a pass to $INPUT, which it can't access,  but not to htmlentities.

**Comment by splitbrain** [comment]
grinder is a static analyzer. what it finds are *possible* problems. you have to analyze and asses them yourself.

**Comment by turnermm** [comment]
Ah, I see.  I didn't know what 'static' referred to.
