### ISSUE TITLE
Implementation of @CURNS@

### ISSUE THREAD

**Issue by grg8** [turnermm/newpagetemplate#8]
Hi!

According to <https://www.dokuwiki.org/plugin:addnewpage#new-page_templates> the [addnewpage](https://www.dokuwiki.org/plugin:addnewpage) plugin enables possibility of inlcuding custom templates via [newpagetemplate](https://www.dokuwiki.org/plugin:newpagetemplate). Therefore, following syntax results in expected behaviour, because newpagetemplate explicitly does not support `@CURNS@` substitution by default as documented:

```
===== @CURNS@ does not work =====
{{NEWPAGE>:custom:namespace#:custom:template}}

===== @CURNS@ works with default __template.txt =====
{{NEWPAGE>:custom:namespace}}
```

As described [here](https://forum.dokuwiki.org/d/18054-namespace-templates-at-curns-at-at-curns-at-at-curns-at-not-working/3) I manually adapted newpagetemplate to process `@CURNS@` replacement according to [default namespace templates](https://www.dokuwiki.org/namespace_templates#replacement_patterns) which is handled inside `inc/common.php`. 

The adaption inside `lib/plugin/newpagetemplate/action.php`: I added the 4 lines between `@NS@` and `@FILE@` and also 4 lines in array below respectively, currently at line 94. Please note that the `$ID` is written in capitals here what is different from default `inc/common.php`:

```
$tpl = str_replace(array(
                              '@ID@',
                              '@NS@',
                              '@CURNS@',
                              '@!CURNS@',
                              '@!!CURNS@',
                              '@!CURNS!@',
                              '@FILE@',
                              '@!FILE@',
                              '@!FILE!@',
                              '@PAGE@',
                              '@!PAGE@',
                              '@!!PAGE@',
                              '@!PAGE!@',
                              '@USER@',
                              '@NAME@',
                              '@MAIL@',
                              '@DATE@',
                              '@EVENT@'
                           ),
                           array(
                              $ID,
                              getNS($ID),
                              curNS($ID),
                              \dokuwiki\Utf8\PhpString::ucfirst(curNS($ID)),
                              \dokuwiki\Utf8\PhpString::ucwords(curNS($ID)),
                              \dokuwiki\Utf8\PhpString::strtoupper(curNS($ID)),
                              $file,
                              utf8_ucfirst($file),
                              utf8_strtoupper($file),
                              $page,
                              utf8_ucfirst($title),
                              utf8_ucwords($title),
                              utf8_strtoupper($title),
                              $_SERVER['REMOTE_USER'],
                              $INFO['userinfo']['name'],
                              $INFO['userinfo']['mail'],
                              $conf['dformat'],
                              $event->name ,
                           ), $tpl);
```

So far, this little adaption seems to work as expected. It is of great worth in our school environment as part of our customized dokuwiki.

I am not a php coder (yet) nor this is a real issue. Maybe this quick hack to enable the `@CURNS@` functionality could be implemented inside this plugin quite easily.

Anyways, thank you for beautiful software!

**Comment by turnermm** [comment]
Thanks for pointing this out.  I adopted this plugin from the original author, because I use it in the openas plugin.  I suspect that when originally written, the CURNS macro wasn't available yet. The original version was started in 2007, and I adopted it about 10 years ago.   I'll try to get around to your fix when I've finished what I'm currently working on.

**Comment by grg8** [comment]
Thanks a lot! I can imagine how precious your time is...

The openas plugin also looks very interesting. I hope to dig a little deeper into the dokuwiki universe as soon as possible (when I've finished what I'm currently working on^^)

**Comment by turnermm** [comment]
This will work only as of now in hogfather: `\dokuwiki\Utf8\PhpString`
Earlier distributions will thrown a class not found error.  However, `ucfirst` will work in both hogfather and earlier.

**Comment by grg8** [comment]
Thx, I can confirm that the following seems to work as well:

```
curNS($ID)),
utf8_ucfirst(curNS($ID)),
utf8_ucwords(curNS($ID)),
utf8_strtoupper(curNS($ID)),
````

Now I realize that compared to the remaining code in the second array it is more consistent.

**Comment by grg8** [comment]
@ https://forum.dokuwiki.org/d/18054-namespace-templates-at-curns-at-at-curns-at-at-curns-at-not-working
